Repository magento/magento2-functional-testing-framework, pull requests merged in 2018-08, with the labels that each got.

#71 magento/magento2-functional-testing-framework#54: Set a global value for timeouts that's used across all wait related actions
  .env.example
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
  src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
  src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Labels: accept, distributed-cd

#217 Support PHP-FPM in command.php
  etc/config/command.php
Labels: acknowledged, in progress

#218 MQE-1236
  dev/tests/unit/Magento/FunctionalTestFramework/Suite/Handlers/SuiteObjectHandlerTest.php
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/TestObjectHandlerTest.php
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/AnnotationExtractorTest.php
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ObjectExtensionUtilTest.php
  dev/tests/verification/Resources/ActionGroupWithDefaultArgumentAndStringSelectorParam.txt
  dev/tests/verification/Resources/ActionGroupWithMultipleParameterSelectorsFromDefaultArgument.txt
  dev/tests/verification/Resources/ActionGroupWithNoArguments.txt
  dev/tests/verification/Resources/ActionGroupWithPassedArgumentAndStringSelectorParam.txt
  dev/tests/verification/Resources/ActionGroupWithSimpleDataUsageFromDefaultArgument.txt
  dev/tests/verification/Resources/ActionGroupWithSimpleDataUsageFromPassedArgument.txt
  dev/tests/verification/Resources/ActionGroupWithSingleParameterSelectorFromDefaultArgument.txt
  dev/tests/verification/Resources/ActionGroupWithSingleParameterSelectorFromPassedArgument.txt
  dev/tests/verification/Resources/BasicFunctionalTest.txt
  dev/tests/verification/Resources/BasicMergeTest.txt
  dev/tests/verification/Resources/ChildExtendedTestAddHooks.txt
  dev/tests/verification/Resources/ChildExtendedTestMerging.txt
  dev/tests/verification/Resources/ChildExtendedTestNoParent.txt
  dev/tests/verification/Resources/ChildExtendedTestRemoveAction.txt
  dev/tests/verification/Resources/ChildExtendedTestRemoveHookAction.txt
  dev/tests/verification/Resources/ChildExtendedTestReplace.txt
  dev/tests/verification/Resources/ChildExtendedTestReplaceHook.txt
  dev/tests/verification/Resources/ExtendingSkippedTest.txt
  dev/tests/verification/Resources/MergedReferencesTest.txt
  dev/tests/verification/Resources/ParentExtendedTest.txt
  dev/tests/verification/Resources/SkippedTest.txt
  dev/tests/verification/Resources/SkippedTestNoIssues.txt
  dev/tests/verification/Resources/SkippedTestTwoIssues.txt
  dev/tests/verification/Resources/SkippedTestWithHooks.txt
  src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
  src/Magento/FunctionalTestingFramework/Test/Util/AnnotationExtractor.php
Labels: approved, bugfix
