Repository magento/magento2-functional-testing-framework, pull requests merged in 2020-03, with the labels that each got.

#611 Small fix to the Mftf Getting Started doc
  docs/getting-started.md
Labels: Award: devdocs update, Partner: Atwix, partners-contribution

#546 #55 Throw Exception when cannot resolve URL attribute
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
  src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
Labels: Partner: Mediotype, Release Line: 3.0, has-jira-ticket, partners-contribution

#641 Lbajsarowicz doc rollup
  docs/best-practices.md
  docs/configuration.md
  docs/img/mftf-extending-precedence.png
  docs/introduction.md
  docs/merging.md
  docs/update.md
  docs/versioning.md
Labels: DOC

#629 DevDocs: Add short explanation on Merging sequence
  docs/img/mftf-extending-precedence.png
  docs/merging.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#628 DevDocs: Update Best Practices
  docs/best-practices.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#627 DevDocs: Add missing information about Backend Domain support.
  docs/configuration.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#625 DevDocs: Update documentation for Introduction page
  docs/introduction.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#626 DevDocs: Update documentation regarding Versioning
  docs/versioning.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#624 DevDocs: Update documentation regarding Update process
  docs/introduction.md
Labels: Award: devdocs update, Partner: Mediotype, partners-contribution

#646 Escaped Liquid tag syntax
  docs/best-practices.md
Labels: DOC

#570 #568 Project-based URN path generation + add consistency of misc.xml path
  src/Magento/FunctionalTestingFramework/Console/GenerateDevUrnCommand.php
Labels: Partner: Mediotype, partners-contribution
