Repository magento/magento2-functional-testing-framework, pull requests merged in 2020-02, with the labels that each got.

#572 Adding deprecation attribute info
  docs/data.md
  docs/metadata.md
  docs/page.md
  docs/section.md
  docs/section/locator-functions.md
  docs/test.md
  docs/test/action-groups.md
Labels: DOC

#573 Quick Fix: PHP's max() requires at least 1 argument
  src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
Labels: Partner: Mediotype, partners-contribution

#562 MFTF Getting Started page improvements
  docs/getting-started.md
Labels: DOC, Partner: Ziffity, partners-contribution

#571 Added missing node
  docs/metadata.md
Labels: Partner: Ziffity, partners-contribution

#561 Example added for grapValueFrom element
  docs/data.md
Labels: Partner: Ziffity, partners-contribution
