Repository magento/magento2-functional-testing-framework, pull requests merged in 2021-07, with the labels that each got.

#841 33307: Eliminated AspectMock usage from GenerationErrorHandlerTest.php
  dev/tests/unit/Magento/FunctionalTestFramework/Util/GenerationErrorHandlerTest.php
Labels: Partner: Atwix, partners-contribution

#854 CE-32868: Updated "monolog" to the latest version 2.3.1
  composer.json
  composer.lock
Labels: Partner: Atwix, accept, in progress, partners-contribution

#846 MFTF-33302: Eliminated AspectMock from ActionGroupObjectTest
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionGroupObjectTest.php
Labels: Partner: Atwix, in progress, partners-contribution

#847 33307: Removed not used mocked object
  dev/tests/unit/Magento/FunctionalTestFramework/Util/GenerationErrorHandlerTest.php
Labels: Partner: Atwix, in progress, partners-contribution

#848 MFTF-33303: Eliminated AspectMock usage from ActionObjectTest
  dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
  dev/tests/unit/Util/MagentoTestCase.php
Labels: Partner: Atwix, in progress, partners-contribution

#866 Add access/secret key config parameters
  docs/configuration.md
Labels: DOC, accept, in progress

#864 MFTF-33585: Eliminated AspectMock usage from TestLoggingUtil
  dev/tests/unit/Util/TestLoggingUtil.php
Labels: Partner: Atwix, in progress, partners-contribution
