Repository magento/magento2-functional-testing-framework, pull requests merged in 2021-06, with the labels that each got.

#830 Add ability to configure multiple OTPs
  dev/tests/verification/Resources/BasicFunctionalTest.txt
  dev/tests/verification/TestModule/Test/BasicFunctionalTest/BasicFunctionalTest.xml
  src/Magento/FunctionalTestingFramework/DataTransport/Auth/Tfa/OTP.php
  src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
  src/Magento/FunctionalTestingFramework/Test/etc/Actions/customActions.xsd
  src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Labels: accept, acknowledged, approved, community-contribution, enhancement, has-jira-ticket, in progress

#833 Eliminated Aspect Mock usage from FilesystemTest
  dev/tests/unit/Magento/FunctionalTestFramework/Config/Reader/FilesystemTest.php
  src/Magento/FunctionalTestingFramework/Config/Reader/Filesystem.php
Labels: accept, acknowledged, approved, in progress

#834 Removed usage of AspectMock in AnnotationsCheckTest.php
  dev/tests/unit/Magento/FunctionalTestFramework/StaticCheck/AnnotationsCheckTest.php
Labels: Partner: EY, accept, acknowledged, approved, in progress, partners-contribution

#838 Removed usage of AspectMock in DeprecatedEntityUsageCheckTest
  dev/tests/unit/Magento/FunctionalTestFramework/StaticCheck/DeprecatedEntityUsageCheckTest.php
Labels: Partner: EY, accept, acknowledged, in progress, partners-contribution
